"""Compile/apply a generated humanoid program using the live public NJC API."""
from riglib.run_options import render_images
import argparse
import itertools
import math
import numpy as np
from pathlib import Path
import time
import json
from riglib.data import read_json, write_json, json_digest
from riglib.live import Live, created_id
from riglib.native_compile import compile_native
from riglib.model import read_model_metadata
from riglib.hierarchy import validate_hierarchy
from riglib.initial_tree import InitialTree
from riglib.part_mesh import verify_mesh
from riglib.carrier import rotation,to_root,to_local
from riglib.resampling import native_axis_distinct
from riglib.grid_automesh import generate as generate_grid_automesh
from riglib.reference_fields import sample


def model_structure(client):
    nodes=[]
    def visit(node,parent=None):
        if node['typeId'] in ('Parameter','Binding'):return
        if not isinstance(node.get('data'),dict):raise ValueError('Missing node census data')
        nodes.append((node['uuid'],node['typeId'],parent))
        for child in node.get('children') or []:visit(child,node['uuid'])
    for node in client.find('*')['items']:visit(node)
    if len({uid for uid,_,_ in nodes})!=len(nodes):raise ValueError('Duplicate node in structure census')
    parameters=client.find('Parameter')['items']
    return sorted(nodes),sorted(p['uuid'] for p in parameters)


def require_single_rig(client,expected_root,expected_bones):
    nodes,_=model_structure(client)
    roots=[uid for uid,kind,parent in nodes if kind=='DepthRigRoot']
    bones=[uid for uid,kind,parent in nodes if kind=='DepthBone']
    if roots!=[expected_root] or set(bones)!=set(expected_bones):
        raise RuntimeError(f'Rig structure mismatch: roots={roots}, bone count={len(bones)}')
    parents={uid:parent for uid,kind,parent in nodes}
    for bone in bones:
        cursor=bone
        while cursor is not None and cursor!=expected_root:cursor=parents[cursor]
        if cursor!=expected_root:raise RuntimeError(f'Bone {bone} is outside the single RigRoot')


def wait_for_baked_key(reader,parameter,targets,key,timeout=300):
    # The native GPU command queues work. A success response is not a commit.
    # Keep this pose unchanged until every requested target has this key.
    deadline=time.monotonic()+timeout
    pending=set(targets);next_report=time.monotonic()+30
    while pending:
        targets_now=sorted(pending)
        responses=reader.read_resources([f'resource://nijigenerate/bindings/get?parameter={parameter}&target={target}&name=deform' for target in targets_now])
        for target,result in zip(targets_now,responses):
            item=result.get('item')
            if item is None:
                if not str(result.get('error','')).startswith('Binding not found:'):raise RuntimeError(result)
                continue
            axes=item['axisValues']
            i=next((i for i,v in enumerate(axes[0]) if abs(v-key[0])<1e-6),None)
            j=next((j for j,v in enumerate(axes[1]) if abs(v-(key[1] if len(key)>1 else 0))<1e-6),None)
            if i is not None and j is not None and item['data']['isSet'][i][j]:pending.remove(target)
        if pending:
            if time.monotonic()>=next_report:
                print(f'Waiting for native key {key}: {len(pending)} targets remain',flush=True)
                next_report=time.monotonic()+30
            if time.monotonic()>deadline:raise RuntimeError(f'Deformation was not committed: parameter={parameter}, key={key}, targets={sorted(pending)}')
            time.sleep(.1)


def apply_registered_fields(n,program,state):
    """Reject obsolete 2D Grid transfer; no Grid keys are written here."""
    if any(d.get('reference_deformations') for d in program['domains']):
        raise ValueError('Direction-specific 2D Grid transfer is forbidden')
    if any(p.get('deformation_authority')!='native_depth_projection' for p in program['parameters']):
        raise ValueError('Every core angle must be generated by native depth and bones')


def apply_program(program, executable, source, output, journal):
    signed=dict(program);signed.pop('content_sha256',None)
    if json_digest(signed)!=program['content_sha256']:raise ValueError('program hash mismatch')
    if program['source'].get('transport')!='njc':
        raise ValueError('Re-observe source through NJC; direct-file observations are not accepted')
    if Path(source).resolve()==Path(output).resolve():raise ValueError('source and output must differ')
    apply_registered_fields(None,program,None)
    n=Live(executable,journal)
    reader=Live(executable)
    # Check generated arrays before any model operation. NJC transport limits
    # must never turn into a different communication or file-editing path.
    for domain in program['domains']:
        n.preflight_call('AutoMesh_SetAdvanced_grid',scale_x=domain['axis_x'],scale_y=domain['axis_y'])
        n.preflight_call('DepthMapCommand_SetDepths',target=4294967295,depths=domain['depths'])
        n.preflight_call('NodeCommand_MoveNode',newParent=4294967295,index=0,
                         context={'nodes':[part['uuid'] for part in domain['parts']]})
    # The open command may be deferred by an application dialog. Verify the
    # actual NJC snapshot before saving or creating anything.
    identity=n.ensure_source(source,program['source']['metadata_sha256'])
    if identity['metadata_sha256']!=program['source']['metadata_sha256']:
        raise ValueError('NJC source snapshot mismatch; no build mutations performed')
    for domain in program['domains']:
        for part in domain['parts']:
            verify_mesh(reader.read(part['uuid'])['item']['data'],
                        {'method':part['mesh_method'],'vertices':part['vertices'],'indices':part['indices']})
    source_structure=model_structure(reader)
    if any(kind in ('DepthRigRoot','DepthBone') for _,kind,_ in source_structure[0]):
        raise ValueError('A new build requires the designated unrigged source INX')
    n.save(output)
    if model_structure(reader)!=source_structure:
        raise RuntimeError('Open did not load the designated source; no rig nodes were created')
    n.call('ToolCommand_ModelEditMode');n.call('ViewportCommand_ResetParameters')
    state={'program_sha256':program['content_sha256'],'bones':{},'grids':{},'groups':{},'parameters':{},'output':str(Path(output).resolve())}
    assigned={p['uuid'] for d in program['domains'] for p in d['parts']}
    references=[uid for uid,kind,parent in source_structure[0] if kind=='Part' and uid not in assigned]
    # Disabled/reference artwork remains in its original render hierarchy.
    # Reparenting it can change inherited visibility and compositing.
    root=created_id(n.call('DepthBoneCommand_CreateDepthRigRoot',parent=program['source_root'],name='Rig::Humanoid'))
    state['rig_root']=root
    for bone in program['scaffold']['bones']:
        uid=created_id(n.call('DepthBoneCommand_AddDepthBone',parent=state['bones'].get(bone['parent'],root),
                             boneId=bone['id'],restHead=bone['head'],restTail=bone['tail'],restRoll=bone['rest_roll']))
        state['bones'][bone['id']]=uid
        if bone['lock_to_root']:n.call('Inspector_Apply_LockToRoot',value=True,context={'nodes':[uid]})
        n.call('DepthBoneCommand_SetDepthBoneConstraint',bone=uid,
               constraint=json.dumps({'allowParentToTargets':bone['allow_parent_to_targets']}))
        if 'pose_origin_z' in bone:
            parent_z=next((b['pose_origin_z'] for b in program['scaffold']['bones'] if b['id']==bone['parent']),0.)
            z=bone['pose_origin_z']-(0. if bone['lock_to_root'] else parent_z)
            n.call('Inspector_Apply_TranslationZ',value=z,context={'nodes':[uid]})
    n.save(output)
    require_single_rig(reader,root,state['bones'].values())
    # Register texture coordinates while source Parts have no authored
    # anatomical children. Changing an origin Part's TRS later would move all
    # its descendants away from their corresponding Bone positions.
    write_json(Path(journal).parent/'native-state.json',state)
    from preserve_source_uv import apply as register_source_uv
    register_source_uv(Path(journal).parent,executable)
    state=read_json(Path(journal).parent/'native-state.json')
    source_nodes=program['hierarchy']['source_nodes']
    ids=[part['uuid'] for d in program['domains'] for part in d['parts']]
    live_parts={uid:r['item']['data'] for uid,r in zip(ids,reader.read_many(ids))}
    for domain in program['domains']:
        for part in domain['parts']:
            uid=part['uuid'];t=live_parts[uid]['transform'];local=np.eye(4)
            local[:2,:2]=rotation(t['rot'][2])@np.diag(t['scale']);local[:3,3]=t['trans']
            parent=source_nodes[str(uid)]['parent']
            world=np.asarray(source_nodes[str(parent)]['matrix'])@local
            source_nodes[str(uid)]['matrix']=world.tolist()
            part['original_transform']={'trans':world[:3,3].tolist(),
                'scale':np.linalg.norm(world[:2,:2],axis=0).tolist(),
                'rot':[0.,0.,float(np.arctan2(world[1,0],world[0,0]))]}
    program['hierarchy'].pop('content_sha256',None)
    program['hierarchy']['content_sha256']=json_digest(program['hierarchy'])
    tree=InitialTree(n,program,state)
    print('Created fitted skeleton',flush=True)
    for index,domain in enumerate(program['domains']):
        parent=program['hierarchy']['render_scope']
        parts=[part['uuid'] for part in domain['parts']]
        tree.prepare_units(domain)
        units=domain['render_units']
        for unit in units:tree.place(unit,parent)
        gid=created_id(n.call('NodeCommand_InsertNode',className='GridDeformer',_suffix='::Surface',context={'nodes':[units[0]]}))
        state['grids'][domain['id']]=gid
        if len(units)>1:n.call('NodeCommand_MoveNode',newParent=gid,index=0,context={'nodes':units[1:]})
        n.call('NodeCommand_SetNodeName',newNames=['Rig::'+domain['id']],context={'nodes':[gid]})
        # Requested axes and the alpha bounds must use the same local frame.
        # Establish the axis-aligned carrier before AutoMesh, preserving the
        # artwork world transforms. Moving it afterwards displaced the sampled
        # depth field relative to its artwork.
        tree.set_carrier(gid,domain,parent)
        state.setdefault('grid_automesh',{})[domain['id']]=generate_grid_automesh(n,gid,domain['axis_x'],domain['axis_y'])
        generated=state['grid_automesh'][domain['id']]
        native_x=generated['generated_axis_x'];native_y=generated['generated_axis_y']
        xy=np.array([[x,y] for y in native_y for x in native_x])
        depth=sample(domain['axis_x'],domain['axis_y'],domain['depth_model_units'],xy)[:,0]
        domain['resampling']['native_automesh_axis_errors']=generated['iterations'][-1]['maximum_axis_errors']
        domain['axis_x']=native_x;domain['axis_y']=native_y
        domain['depth_model_units']=depth.tolist()
        domain['depths']=np.round(depth/program['native_depth_scale'],6).tolist()
        domain['automesh_coordinate_authority']='carrier_local_native_precision_v1'
        for part in domain['parts']:
            verify_mesh(reader.read(part['uuid'])['item']['data'],{'method':part['mesh_method'],'vertices':part['vertices'],'indices':part['indices']})
        generated=state['grid_automesh'][domain['id']]
        moved=reader.read(gid)['item']['data']
        if any(moved['grid_axis_'+axis]!=generated['generated_axis_'+axis] for axis in ('x','y')):
            raise ValueError('Carrier placement changed native AutoMesh axes')
        n.call('DepthMapCommand_SetDepths',target=gid,depths=domain['depths'])
        for source_name in domain['bone_sources']:
            n.call('DepthBoneCommand_AddDepthBoneSource',root=root,target=gid,bone=state['bones'][source_name])
        # Keep the native default unless the registered component explicitly
        # supplies a reference rule. Expanding the radius to cover geometry is
        # not a structural fix and changes the parent's inherited motion.
        if 'bone_influence_rule' in domain:
            n.call('DepthBoneCommand_SetDepthBoneInfluenceRule',root=root,target=gid,
                   rule=json.dumps(domain['bone_influence_rule']))
            domain['bone_influence_authority']='registered_reference'
        else:
            domain['bone_influence_authority']='native_default'
        binding=next(b for b in reader.read(root)['item']['data']['bindings'] if b['target']==gid)
        domain['bone_influence_rule']=binding['influenceRule']
        print(f'Surface {index+1}/{len(program["domains"])} {domain["id"]}',flush=True)
    tree.assemble()
    from riglib.shoulder_welding import apply as apply_shoulder_welding
    state['shoulder_welding']=apply_shoulder_welding(n,program,Path(journal).parent)
    from riglib.composite_mesh import build as build_composite_meshes
    state['composite_automesh']=build_composite_meshes(tree,read_json(Path(journal).parent/'evidence.json'),
        read_json(Path(__file__).resolve().parent.parent/'structures/composite-automesh.json'))
    program.pop('content_sha256',None);program['content_sha256']=json_digest(program)
    state['program_sha256']=program['content_sha256']
    write_json(Path(journal).parent/'program.json',program)
    n.save(output)
    require_single_rig(reader,root,state['bones'].values())
    write_json(Path(journal).parent/'native-state.json',state)
    write_json(Path(journal).parent/'hierarchy-applied.json',validate_hierarchy(reader,state,program))
    n.call('ViewportCommand_FitViewportToModel')
    if render_images(Path(journal).parent): n.call('ViewCommand_SaveScreenshot',filename=str(Path(journal).parent/'structure-neutral.png'))
    for spec in program['parameters']:
        n.call('ViewportCommand_ResetParameters')
        if spec['vec2']:
            uid=created_id(n.call('ParamCommand_Add2DParameter',min=-1,max=1))
        else:
            uid=created_id(n.call('ParamCommand_Add1DParameter',min=-1,max=1))
        state['parameters'][spec['name']]=uid
        n.call('ParamPropCommand_SetParameterName',newName=spec['name'],context={'parameters':[uid]})
        axis=[0,.25,.5,.75,1]
        n.call('ParamPropCommand_ApplyParameterPropsAxes',min=[-1,-1 if spec['vec2'] else 0],max=[1,1 if spec['vec2'] else 0],axisX=axis,axisY=axis if spec['vec2'] else [],context={'parameters':[uid]})
        keys=list(itertools.product([-1,-.5,0,.5,1],repeat=2)) if spec['vec2'] else [(x,) for x in [-1,-.5,0,.5,1]]
        for binding in spec['bindings']:
            for key in keys:
                context={'parameters':[uid],'nodes':[state['bones'][binding['bone']]],'parameterValue':list(key)}
                angle=binding['degrees']*key[binding['input']]
                if binding['axis'] in ('x','y'):
                    tool='ModelCommand_SetRotation'+binding['axis'].upper()+'Binding'
                    n.call(tool,rotationRadians=math.radians(angle),context=context)
                else:
                    n.call('ModelCommand_SetTRSBinding',translation=[],scale=[],rotationDegrees=angle,applyRotation=True,context=context)
        if spec.get('deformation_authority') == 'native_depth_projection':
            curves=spec['reference_curves'];length=program['reference_template']['torso_length']
            for bone in sorted({c['bone'] for c in curves}):
                fields={c['property']:c for c in curves if c['bone']==bone}
                for i,x in enumerate([-1,-.5,0,.5,1]):
                    for j,y in enumerate([-1,-.5,0,.5,1] if spec['vec2'] else [0]):
                        context={'parameters':[uid],'nodes':[state['bones'][bone]],'parameterValue':[x,y]}
                        for axis in ('x','y'):
                            prop='transform.r.'+axis
                            if prop in fields:n.call('ModelCommand_SetRotation'+axis.upper()+'Binding',
                                rotationRadians=fields[prop]['values'][i][j],context=context)
                        tr=[]
                        if any('transform.t.'+a in fields for a in ('x','y')):
                            tr=[fields['transform.t.'+a]['values'][i][j]*length if 'transform.t.'+a in fields else 0. for a in ('x','y')]
                        rz=fields.get('transform.r.z')
                        if tr or rz:n.call('ModelCommand_SetTRSBinding',translation=tr,scale=[],
                            rotationDegrees=math.degrees(rz['values'][i][j]) if rz else 0.,applyRotation=bool(rz),context=context)
            n.call('ViewportCommand_ResetParameters');n.save(output)
            write_json(Path(journal).parent/'native-state.json',state)
            print('Prepared common reference drivers '+spec['name'],flush=True)
            continue
        for key in keys:
            n.call('ParameditCommand_SetArmedParameterAndKeypoint',context={'armedParameters':[uid],'parameterValue':list(key)})
            n.call('DepthBoneCommand_ApplyDepthBoneDeform',root=root,targets='',context={'armedParameters':[uid]})
            wait_for_baked_key(reader,uid,state['grids'].values(),key)
        n.call('ViewportCommand_ResetParameters')
        n.save(output)
        require_single_rig(reader,root,state['bones'].values())
        write_json(Path(journal).parent/'native-state.json',state)
        print(f'Baked {spec["name"]}',flush=True)
    apply_registered_fields(n,program,state)
    n.call('ToolCommand_ModelEditMode');n.call('ViewportCommand_ResetParameters')
    n.call('ViewportCommand_ResetParameters')
    n.save(output)
    require_single_rig(reader,root,state['bones'].values())
    write_json(Path(journal).parent/'hierarchy-applied.json',validate_hierarchy(reader,state,program))
    return state


def main():
    p=argparse.ArgumentParser()
    p.add_argument('--observation',required=True);p.add_argument('--assembly',required=True);p.add_argument('--evidence',required=True)
    p.add_argument('--prior',default=str(Path(__file__).resolve().parents[1]/'structures'/'humanoid-prior.json'))
    p.add_argument('--program',required=True);p.add_argument('--apply',action='store_true')
    p.add_argument('--njc');p.add_argument('--source');p.add_argument('--out');p.add_argument('--journal')
    a=p.parse_args()
    program=compile_native(read_json(a.observation),read_json(a.assembly),read_json(a.evidence),read_json(a.prior))
    write_json(a.program,program)
    print(f'Compiled {len(program["domains"])} domains and {len(program["parameters"])} drivers',flush=True)
    if a.apply:
        if not all([a.njc,a.source,a.out,a.journal]):p.error('--apply requires --njc --source --out --journal')
        apply_program(program,a.njc,a.source,a.out,a.journal)


if __name__=='__main__':main()
